export PATH="$PATH:./node_modules/.bin"

alias gcl="git clone"
alias gco="git checkout"
alias gcb="git checkout -B"
alias gp="git push"
alias gst="git status"
alias gpl="git pull"
alias gm="git merge"
alias gb="git branch"
alias nah="git reset --hard"
